"""
Het logo van leer.nu, uit de levering van de ontwerper (ADR-113, ADR-147).

De ontwerper leverde het beeldmerk als SVG (de ring met het naaldje) en het
woordbeeld als paden: docs/logo/svg/leernu-woordbeeld-*.svg, Hanken Grotesk 500.
Dat woordbeeld hoeft dus niet meer uit een lettertype gesneden te worden; de
paden staan overgenomen in src/design/woordbeeld.ts, en logo.test.ts houdt ze
aan het bestand. Dit script raakt het woordbeeld niet aan, behalve om de
sociale kaart ervan te tekenen.

Wat dit schrijft:

- docs/logo/svg/favicon.svg: de ring zonder naald op een inktvlak (onder 20 px
  valt het naaldje weg, zegt de uitwerking);
- src/design/logo.ts: de maten van het beeldmerk, voor Brandmark;
- public/logo/: de favicon, de app-iconen en de sociale kaart.

De kleuren komen uit de styleguide ("Leisteen"): de letters staan in inkt en de
ring van het merk in de actiekleur, zoals de styleguide het merk in de balk
tekent. De levering in docs/logo/png blijft zoals de ontwerper hem gaf; wat naar
public/logo gaat wordt hier omgekleurd, zodat er maar een plek is waar de kleur
van het logo staat.

Draaien vanuit de root van de repo:  python tools/logo/maak-logo.py
Nodig: Pillow en CairoSVG.
"""

import io
import shutil
from pathlib import Path

import cairosvg

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[2]
LOGO = ROOT / "docs" / "logo"

# De styleguide, §02 en §07. Inkt en papier zijn precies --inkt en --kaart uit
# src/index.css, de ring is --merk: de actiekleur, de enige kleur die in dit
# product "hier druk je op" betekent en dus ook de kleur van het merk.
INKT = "#1B2230"
PAPIER = "#FFFFFF"
RING = "#385DB8"

# Wat de ontwerper leverde, in de kleuren van toen: waar de omkleuring vandaan
# rekent (herkleur). De levering zelf blijft ongemoeid.
LEVERING_INKT = (26, 32, 27)
LEVERING_PAPIER = (251, 250, 246)

# Het beeldmerk, in het vak van 100 uit beeldmerk-inkt.svg.
MERK = {"cx": 50, "cy": 50, "r": 38, "stroke": 13}
NAALD = [(31, 41), (69, 41), (50, 65)]
# Onder 20 px: alleen de ring, dikker (de favicon van 16 in de uitwerking).
MERK_KLEIN = {"r": 36, "stroke": 18}


def herkleur(beeld: Image.Image) -> Image.Image:
    """De levering (twee kleuren met antialiasing ertussen) in de huisstijl.

    Elke pixel is een menging van de inkt en het papier van toen. Hoeveel van
    elk, leest het groene kanaal af — de twee liggen daar 218 stappen uit
    elkaar — en met datzelfde mengsel worden de nieuwe twee gemengd. Zo blijven
    de randen zacht en verschuift alleen de kleur. De doorzichtige hoeken van
    een icoon krijgen de nieuwe inkt mee, zodat er bij het verkleinen geen
    zwarte rand uit tevoorschijn komt.
    """
    beeld = beeld.convert("RGBA")
    laag, hoog = LEVERING_INKT[1], LEVERING_PAPIER[1]
    mengsel = beeld.getchannel("G").point(
        lambda v: max(0, min(255, round((hoog - v) * 255 / (hoog - laag))))
    )
    uit = Image.composite(
        Image.new("RGB", beeld.size, INKT), Image.new("RGB", beeld.size, PAPIER), mengsel
    ).convert("RGBA")
    uit.putalpha(beeld.getchannel("A"))
    return uit


def main() -> None:
    # --- docs/logo/svg -----------------------------------------------------
    svg_map = LOGO / "svg"
    svg_map.mkdir(parents=True, exist_ok=True)

    # De favicon: het tegeltje van 16 uit de uitwerking. Onder 20 px valt het
    # naaldje weg en blijft de ring over.
    k = 11 / 100
    favicon = (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">'
        f'<rect width="16" height="16" rx="4" fill="{RING}"/>'
        f'<circle cx="8" cy="8" r="{round(MERK_KLEIN["r"] * k, 2)}" '
        f'fill="none" stroke="{PAPIER}" stroke-width="{round(MERK_KLEIN["stroke"] * k, 2)}"/></svg>\n'
    )
    (svg_map / "favicon.svg").write_text(favicon, encoding="utf-8")

    # --- src/design/logo.ts ------------------------------------------------
    ts = f"""/**
 * The beeldmerk, as numbers (ADR-113). Generated by tools/logo/maak-logo.py —
 * do not edit by hand; run the script again.
 *
 * A ring with a needle, on the box of 100 of the designer's beeldmerk-inkt.svg.
 * The woordbeeld is no longer drawn from it: that is the designer's own
 * outlines, in woordbeeld.ts (ADR-147). logo.test.ts holds these numbers to
 * docs/logo/svg.
 */

/** The beeldmerk on its own, on the box of 100 of beeldmerk-inkt.svg. */
export const MERK = {{
  size: 100,
  cx: {MERK["cx"]},
  cy: {MERK["cy"]},
  r: {MERK["r"]},
  stroke: {MERK["stroke"]},
  naald: 'M31 41 L69 41 L50 65 Z',
}} as const;

/** Below {20} px the needle goes and the ring is drawn heavier, as the favicon is. */
export const MERK_KLEIN = {{ r: {MERK_KLEIN["r"]}, stroke: {MERK_KLEIN["stroke"]} }} as const;
export const MERK_NAALD_VANAF_PX = 20;
"""
    (ROOT / "src" / "design" / "logo.ts").write_text(ts, encoding="utf-8", newline="\n")

    # --- public/logo -------------------------------------------------------
    png = LOGO / "png"
    pub = ROOT / "public" / "logo"
    (pub / "svg").mkdir(parents=True, exist_ok=True)
    (pub / "png").mkdir(parents=True, exist_ok=True)
    shutil.copyfile(svg_map / "favicon.svg", pub / "svg" / "favicon.svg")

    # De favicon en het app-icoon: het merk uit een vlak gespaard, dus een
    # tekening in een kleur — omkleuren volstaat. Het vlak wordt de kleur van
    # het merk en het merk het licht.
    def tegel(bestand: str) -> Image.Image:
        beeld = herkleur(Image.open(png / bestand))
        vlak = Image.new("RGBA", beeld.size, RING)
        merk = Image.new("RGBA", beeld.size, PAPIER)
        # Het mengsel opnieuw: wat inkt was wordt het vlak, wat papier was het merk.
        laag, hoog = LEVERING_INKT[1], LEVERING_PAPIER[1]
        mengsel = Image.open(png / bestand).convert("RGBA").getchannel("G").point(
            lambda v: max(0, min(255, round((v - laag) * 255 / (hoog - laag))))
        )
        uit = Image.composite(merk, vlak, mengsel).convert("RGBA")
        uit.putalpha(Image.open(png / bestand).convert("RGBA").getchannel("A"))
        return uit

    tegel("favicon-32.png").save(pub / "png" / "favicon-32.png")

    # De sociale kaart is het woordbeeld midden op een kaart: opnieuw getekend
    # uit het geleverde woordbeeld, in de kleuren waarin het op papier staat.
    # De maat is die van de levering: 384 breed, in het midden van 1200 bij 630.
    kaart = Image.open(
        io.BytesIO(
            cairosvg.svg2png(
                bytestring=(svg_map / "leernu-woordbeeld-positief.svg").read_bytes(),
                output_width=384 * 2,
            )
        )
    ).convert("RGBA")
    doek = Image.new("RGB", (1200 * 2, 630 * 2), PAPIER)
    doek.paste(kaart, ((1200 * 2 - kaart.width) // 2, (630 * 2 - kaart.height) // 2), kaart)
    doek.resize((1200, 630), Image.LANCZOS).save(pub / "png" / "social-kaart-1200x630.png")

    # The rounded icon as delivered, for the manifest's "any".
    icoon = tegel("app-icoon-1024.png")
    for maat in (192, 512):
        icoon.resize((maat, maat), Image.LANCZOS).save(pub / "png" / f"app-icoon-{maat}.png")

    # Full bleed, for iOS (which rounds the corners itself) and for Android's
    # maskable, whose safe zone the mark already sits inside: the app icon's
    # own proportions, a mark of 532 on 1024.
    def vol(maat: int) -> Image.Image:
        groot = maat * 4
        beeld = Image.new("RGB", (groot, groot), RING)
        teken = ImageDraw.Draw(beeld)
        kk = 532 / 1024 * groot / 100
        o = (groot - 100 * kk) / 2
        c = groot / 2
        buiten = MERK["r"] * kk + MERK["stroke"] * kk / 2
        teken.ellipse(
            [c - buiten, c - buiten, c + buiten, c + buiten],
            outline=PAPIER,
            width=round(MERK["stroke"] * kk),
        )
        teken.polygon([(o + px * kk, o + py * kk) for px, py in NAALD], fill=PAPIER)
        return beeld.resize((maat, maat), Image.LANCZOS)

    vol(180).save(pub / "png" / "apple-touch-icon-180.png")
    vol(512).save(pub / "png" / "app-icoon-maskable-512.png")



if __name__ == "__main__":
    main()
