import type { TranslationKey } from '@/i18n';

/**
 * Wat je kunt als je een diploma haalt, per diploma (ADR-219): "Je rekent de
 * hele tafel van 7 uit je hoofd. Ook 7 × 8." Het herontwerp van het diploma
 * vroeg een zin per onderwerp in plaats van één per vak.
 *
 * Een lijst met de sleutels voluit, zodat de toets op ongebruikte teksten ze
 * vindt; `diplomaZinnen.test.ts` eist er een voor elk diploma.
 */
export const DIPLOMA_ZIN: Readonly<Record<string, TranslationKey>> = {
  'nl-provincies': 'diploma.zin.nl-provincies',
  'nl-hoofdsteden': 'diploma.zin.nl-hoofdsteden',
  'nl-waddeneilanden': 'diploma.zin.nl-waddeneilanden',
  'nl-wateren': 'diploma.zin.nl-wateren',
  'nl-steden': 'diploma.zin.nl-steden',
  'europa-landen': 'diploma.zin.europa-landen',
  'afrika-landen': 'diploma.zin.afrika-landen',
  'azie-landen': 'diploma.zin.azie-landen',
  'noord-amerika-landen': 'diploma.zin.noord-amerika-landen',
  'zuid-amerika-landen': 'diploma.zin.zuid-amerika-landen',
  'oceanie-landen': 'diploma.zin.oceanie-landen',
  'wereld-landen': 'diploma.zin.wereld-landen',
  'tafel-1': 'diploma.zin.tafel-1',
  'tafel-2': 'diploma.zin.tafel-2',
  'tafel-3': 'diploma.zin.tafel-3',
  'tafel-4': 'diploma.zin.tafel-4',
  'tafel-5': 'diploma.zin.tafel-5',
  'tafel-6': 'diploma.zin.tafel-6',
  'tafel-7': 'diploma.zin.tafel-7',
  'tafel-8': 'diploma.zin.tafel-8',
  'tafel-9': 'diploma.zin.tafel-9',
  'tafel-10': 'diploma.zin.tafel-10',
  'tafel-11': 'diploma.zin.tafel-11',
  'tafel-12': 'diploma.zin.tafel-12',
  'keer-100': 'diploma.zin.keer-100',
  'keer-1000': 'diploma.zin.keer-1000',
  'delen-10': 'diploma.zin.delen-10',
  'delen-100': 'diploma.zin.delen-100',
  'delen-1000': 'diploma.zin.delen-1000',
  'plus-20': 'diploma.zin.plus-20',
  'plus-100': 'diploma.zin.plus-100',
  'plus-1000': 'diploma.zin.plus-1000',
  'min-20': 'diploma.zin.min-20',
  'min-100': 'diploma.zin.min-100',
  'min-1000': 'diploma.zin.min-1000',
  'splitsen-10': 'diploma.zin.splitsen-10',
  'splitsen-20': 'diploma.zin.splitsen-20',
  'splitsen-100': 'diploma.zin.splitsen-100',
  'halveren-20': 'diploma.zin.halveren-20',
  'halveren-100': 'diploma.zin.halveren-100',
  'halveren-1000': 'diploma.zin.halveren-1000',
  'verdubbelen-20': 'diploma.zin.verdubbelen-20',
  'verdubbelen-100': 'diploma.zin.verdubbelen-100',
  'verdubbelen-1000': 'diploma.zin.verdubbelen-1000',
  'klok-heel': 'diploma.zin.klok-heel',
  'klok-half': 'diploma.zin.klok-half',
  'klok-kwart': 'diploma.zin.klok-kwart',
  'klok-vijf': 'diploma.zin.klok-vijf',
  'vlag-nederland-provincies': 'diploma.zin.vlag-nederland-provincies',
  'vlag-afrika-alle': 'diploma.zin.vlag-afrika-alle',
  'vlag-azie-alle': 'diploma.zin.vlag-azie-alle',
  'vlag-europa-alle': 'diploma.zin.vlag-europa-alle',
  'vlag-noord-amerika-alle': 'diploma.zin.vlag-noord-amerika-alle',
  'vlag-zuid-amerika-alle': 'diploma.zin.vlag-zuid-amerika-alle',
  'vlag-oceanie-alle': 'diploma.zin.vlag-oceanie-alle',
  'taal-sp-eiij': 'diploma.zin.taal-sp-eiij',
  'taal-sp-auou': 'diploma.zin.taal-sp-auou',
  'taal-sp-gch': 'diploma.zin.taal-sp-gch',
  'taal-sp-ck': 'diploma.zin.taal-sp-ck',
  'taal-sp-dt': 'diploma.zin.taal-sp-dt',
  'taal-sp-klinkers': 'diploma.zin.taal-sp-klinkers',
  'taal-sp-medeklinkers': 'diploma.zin.taal-sp-medeklinkers',
  'taal-sp-verkleinwoorden': 'diploma.zin.taal-sp-verkleinwoorden',
  'taal-sp-ig': 'diploma.zin.taal-sp-ig',
  'taal-sp-lijk': 'diploma.zin.taal-sp-lijk',
  'taal-ww-tt': 'diploma.zin.taal-ww-tt',
  'taal-ww-vt': 'diploma.zin.taal-ww-vt',
  'taal-ww-vd': 'diploma.zin.taal-ww-vd',
  'taal-en-getallen': 'diploma.zin.taal-en-getallen',
  'taal-en-dagen': 'diploma.zin.taal-en-dagen',
  'taal-en-kleuren': 'diploma.zin.taal-en-kleuren',
  'taal-en-kleding': 'diploma.zin.taal-en-kleding',
  'taal-en-familie': 'diploma.zin.taal-en-familie',
  'taal-en-lichaam': 'diploma.zin.taal-en-lichaam',
  'taal-en-dieren': 'diploma.zin.taal-en-dieren',
  'taal-en-eten': 'diploma.zin.taal-en-eten',
  'taal-en-huis': 'diploma.zin.taal-en-huis',
  'taal-en-school': 'diploma.zin.taal-en-school',
  'taal-en-werkwoorden': 'diploma.zin.taal-en-werkwoorden',
};
