/**
 * The logo, as path data (ADR-113). Generated by tools/logo/maak-logo.py —
 * do not edit by hand; run the script again.
 *
 * The wordmark is Hanken Grotesk 600, cut to outlines from the font embedded in
 * the designer's own uitwerking (docs/logo/uitwerking), with the letter spacing
 * and the kerning it sets — so the name needs no font and is the same on every
 * machine. Between the words stands the beeldmerk: a ring with a needle,
 * lifted 15.2 units off the baseline as the uitwerking draws it.
 * logo.test.ts holds these numbers to docs/logo/svg.
 */

/** The wordmark's drawing box: the letters stand on the baseline at its bottom. */
export const LOCKUP = { width: 3187.1, height: 697 } as const;

/** How far the round letters dip below the baseline, drawn outside the box. */
export const LOCKUP_DOORZAKKEN = 9.2;

/** The x-height of the letters, in the box's units: what a path behind the name matches. */
export const LOCKUP_X_HOOGTE = 493;

/** l, e, e, r, n, u — each already in its place in the box. */
export const LOCKUP_GLYPHS: readonly string[] = [
  'M111.8 706.2Q63.2 706.2 31.6 676.4Q0 646.6 0 581.6V0H110.4V560Q110.4 583.4 121 593.6Q131.6 603.8 148.8 603.8Q157.4 603.8 167 602Q176.6 600.2 187 597V691.4Q167.6 699.2 147.6 702.7Q127.6 706.2 111.8 706.2Z',
  'M471.4 706.2Q409.4 706.2 364.1 685.9Q318.8 665.6 289.7 630Q260.6 594.4 246.5 548.9Q232.4 503.4 232.4 453.6Q232.4 404.6 246.2 358.3Q260 312 287.9 275.2Q315.8 238.4 359.6 216.6Q403.4 194.8 463.4 194.8Q520.8 194.8 563.3 214.3Q605.8 233.8 633.5 268.2Q661.2 302.6 675 347Q688.8 391.4 688.8 441.2Q688.8 447.6 688.3 460.7Q687.8 473.8 685.8 486.8H343.2Q347.4 546 383.4 577.2Q419.4 608.4 476 608.4Q516.2 608.4 550.6 595Q585 581.6 613 554.2L674 627.8Q642.2 655.6 611.4 672.9Q580.6 690.2 547.1 698.2Q513.6 706.2 471.4 706.2ZM579.2 431Q581.2 423 582.1 415Q583 407 583 399.4Q583 377.4 575.1 357.2Q567.2 337 552.3 321.3Q537.4 305.6 515.7 296.5Q494 287.4 465.8 287.4Q426.8 287.4 400 304.2Q373.2 321 359 347.6Q344.8 374.2 341.8 404.6H616Z',
  'M992.4 706.2Q930.4 706.2 885.1 685.9Q839.8 665.6 810.7 630Q781.6 594.4 767.5 548.9Q753.4 503.4 753.4 453.6Q753.4 404.6 767.2 358.3Q781 312 808.9 275.2Q836.8 238.4 880.6 216.6Q924.4 194.8 984.4 194.8Q1041.8 194.8 1084.3 214.3Q1126.8 233.8 1154.5 268.2Q1182.2 302.6 1196 347Q1209.8 391.4 1209.8 441.2Q1209.8 447.6 1209.3 460.7Q1208.8 473.8 1206.8 486.8H864.2Q868.4 546 904.4 577.2Q940.4 608.4 997 608.4Q1037.2 608.4 1071.6 595Q1106 581.6 1134 554.2L1195 627.8Q1163.2 655.6 1132.4 672.9Q1101.6 690.2 1068.1 698.2Q1034.6 706.2 992.4 706.2ZM1100.2 431Q1102.2 423 1103.1 415Q1104 407 1104 399.4Q1104 377.4 1096.1 357.2Q1088.2 337 1073.3 321.3Q1058.4 305.6 1036.7 296.5Q1015 287.4 986.8 287.4Q947.8 287.4 921 304.2Q894.2 321 880 347.6Q865.8 374.2 862.8 404.6H1137Z',
  'M1297.4 697V204H1409.2V337.2L1388.8 340.2Q1393.4 297 1417.5 264.3Q1441.6 231.6 1475.9 213.2Q1510.2 194.8 1544.6 194.8Q1568.8 194.8 1590.8 200.8Q1612.8 206.8 1636.4 220.8L1582.4 320.8Q1571.2 314.4 1554.1 309.8Q1537 305.2 1520.8 305.2Q1499.6 305.2 1479.3 313Q1459 320.8 1443 337.2Q1427 353.6 1418.2 380.4Q1413.8 394.4 1411.3 416.5Q1408.8 438.6 1408.8 478.8V697Z',
  'M2220.1 697V204H2331.5V313.4L2311.5 317.6Q2324.7 274.8 2349.5 247.9Q2374.3 221 2407.7 207.9Q2441.1 194.8 2478.1 194.8Q2561.1 194.8 2607.9 242.3Q2654.7 289.8 2654.7 378V697H2543.3V419Q2543.3 352.8 2519.4 321.9Q2495.5 291 2445.5 291Q2408.1 291 2382.8 308.4Q2357.5 325.8 2344.5 362.7Q2331.5 399.6 2331.5 457.4V697Z',
  'M2930.3 706.2Q2872.5 706.2 2832.7 683.1Q2792.9 660 2773 616.8Q2753.1 573.6 2753.1 513.2V204H2863.9V482.8Q2863.9 521.8 2873.4 550.3Q2882.9 578.8 2904.7 594.1Q2926.5 609.4 2963.1 609.4Q3006.1 609.4 3030.6 586.5Q3055.1 563.6 3065.7 520.4Q3076.3 477.2 3076.3 416.2V204H3187.1V697H3076.3V590.8L3094.9 597.6Q3072.7 653.8 3028.9 680Q2985.1 706.2 2930.3 706.2Z',
];

/** The beeldmerk between the words: a ring, and the needle inside it. */
export const LOCKUP_MERK = {
  cx: 1894,
  cy: 443.2,
  r: 181.4,
  stroke: 62,
  naald: 'M1803.3 400.3 L1984.6 400.3 L1894 514.8 Z',
} as const;

/** The beeldmerk on its own, on the box of 100 of beeldmerk-inkt.svg. */
export const MERK = {
  size: 100,
  cx: 50,
  cy: 50,
  r: 38,
  stroke: 13,
  naald: 'M31 41 L69 41 L50 65 Z',
} as const;

/** Below 20 px the needle goes and the ring is drawn heavier, as the favicon is. */
export const MERK_KLEIN = { r: 36, stroke: 18 } as const;
export const MERK_NAALD_VANAF_PX = 20;

/** The smallest the wordmark is drawn, in px of box height. */
export const LOCKUP_MIN_PX = 20;
