/**
 * The beeldmerk, as numbers (ADR-113). Generated by tools/logo/maak-logo.py —
 * do not edit by hand; run the script again.
 *
 * A ring with a needle, on the box of 100 of the designer's beeldmerk-inkt.svg.
 * The woordbeeld is no longer drawn from it: that is the designer's own
 * outlines, in woordbeeld.ts (ADR-147). logo.test.ts holds these numbers to
 * docs/logo/svg.
 */

/** The beeldmerk on its own, on the box of 100 of beeldmerk-inkt.svg. */
export const MERK = {
  size: 100,
  cx: 50,
  cy: 50,
  r: 38,
  stroke: 13,
  naald: 'M31 41 L69 41 L50 65 Z',
} as const;

/** Below 20 px the needle goes and the ring is drawn heavier, as the favicon is. */
export const MERK_KLEIN = { r: 36, stroke: 18 } as const;
export const MERK_NAALD_VANAF_PX = 20;
